server:
  port: ${PORT:8080}

spring:
  application:
    name: mercadox
  # config:
  #   import: optional:file:.env[.properties]  

  datasource:
    # url: jdbc:mysql://mercadox-db.ctoyecue2hb3.us-east-2.rds.amazonaws.com:3306/mercadox?useSSL=false&allowPublicKeyRetrieval=true
    # username: root
    # password: 6bckDumTc71w2Ys3dO5B
    url: ${DB_URL:jdbc:mysql://mercadox-db.ctoyecue2hb3.us-east-2.rds.amazonaws.com:3306/mercadox?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:6bckDumTc71w2Ys3dO5B}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Bogota

jwt:
  secret: "Zm9yX3Rlc3RpbmdfcHVycG9zZXNfb25seV9zZWNyZXRfa2V5XzMyYnl0ZXM="
  accessTokenExpiration: 900000000 # 15000 minutos

  # ============================================
  # Email service
  # ============================================   
sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: juanp.rodriguezg@uqvirtual.edu.co
  from-name: Mercadox

logging:
  level:
    root: INFO
    com.mercadox: DEBUG
    com.mercadox.repositories: DEBUG
    com.mercadox.services: DEBUG
    com.mercadox.services.storage: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG